# Generated by Django 5.1.1 on 2024-09-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_image', models.ImageField(upload_to='image/')),
                ('stu_resume', models.FileField(upload_to='Files/')),
            ],
        ),
    ]
